# Plugin made by Lacys

# This is the strength of the velocity of the tnt when the player
# right clicks
multiply: 2     # default: 2

# TNT will explode after this amount of time
fuseTicks: 100     # default: 100

# Cooldown in ticks
cooldown: 0     # default: 0